name: V2ex签到

on:
    workflow_dispatch:
    schedule:
        - cron: "01 04 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                python-version: 3.10.16

            - name: "安装依赖包"
              run: pip install -r ./requirements.txt

            - name: "运行【V2ex自动签到】"
              run: python3 function/v2ex/v2ex.py
              env:
                  V2EXCK: ${{ secrets.V2EXCK }}
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN}}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER}}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                  QYWX_AM: ${{ secrets.QYWX_AM}}
#最后推送 2021年4月22日
